bcgov/ehpr2

- apps/web/src/components/submission/index.tsx
Preemptive bugfix here, this should be a bit better
> add horizontal padding to mobile form

- apps/web/src/components/Header.tsx
- apps/web/src/pages/submission/[step].tsx
- update header text
- scroll to the top of the form at step transitions
- do not scroll at initial loading
- rollback logo to img element
[exportPathMap](https://nextjs.org/docs/api-reference/next.config.js/exportPathMap) should be defined in `next.config.js` in order to benefit from `image optimization`. But it can't be available because of dynamic paths.
> EHPR-105 scroll to the top of the form

- .github/workflows/pr-check-api.yml
- .github/workflows/pr-check-common.yml
- .github/workflows/pr-check-terraform.yml
- .github/workflows/pr-check-web.yml
When branching away from main we don't get PR checks, this changes that so checks run on all PRs
> Don't limit checks to main branch PRs

- packages/common/src/dto/availability-information.dto.ts
https://freshworks.atlassian.net/browse/EHPR-165
IsIn was being validated before IsString causing the wrong message to appear
> EHPR-165 | Change order of validations

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-test.yml
- packages/common/src/dto/is-array-of-specialties.decorator.ts
https://freshworks.atlassian.net/browse/EHPR-150
we were incorrectly checking `specialty.name` which caused the `continue` block to run thus returning the default message
> EHPR-150 | Fix specialty error message

- apps/api/src/app.config.ts
- packages/common/src/dto/skill-information.dto.ts
The issue with re-enabling validation was that health authorities wasn't being assigned in the DTO constructor, seems to be all working now.
https://freshworks.atlassian.net/browse/EHPR-147
Related tickets created:
- Bug: [Array contents are not validated](https://freshworks.atlassian.net/browse/EHPR-185)
- Task: [Log API validation errors in an understandable format](https://freshworks.atlassian.net/browse/EHPR-184)
> EHPR-147 | Re-enable validation

- apps/web/src/components/Advisory.tsx
- apps/web/src/components/Alert.tsx
- apps/web/src/components/index.tsx
- apps/web/src/components/submission/components/Review.tsx
- apps/web/tailwind.config.js
> Added notice

- apps/api/src/app.config.ts
- apps/api/src/common/error-exception.filter.ts
- packages/common/src/dto/is-valid-lha.decorator.ts
- packages/common/src/dto/is-valid-submission.decorator.ts
- Fix error filter logging errors twice
- Fix error filter private keys implementation
- Fix LHA array validator naming
- Filter payload from error so we don't log PII
- Fix error logging parameters
- Use `defaultMessage` + `exceptionFactory` to expose validation error messages
I really hamfisted through this so I'm expecting some comments on how to clean this up a bit :\ also the response is heavily nested arrays which I think checks out because of the nested nature of our data, but maybe we can improve that as well
> EHPR-184 | Logging API Validations

- packages/common/src/validators/is-array-of-specialties.decorator.ts
https://freshworks.atlassian.net/browse/EHPR-192
- We were accidentally passing the list of specialties instead of the current list of subspecialties to the `subspecialtyNotListed` method
> EHPR-192 | Fix specialty selector error message

- .config/.env-example
- Makefile
- Add easy env switching for db tunnel
- Add some info logs in db tunnel
> Prod Bastion Host

- Makefile
- apps/api/src/app.controller.ts
- apps/web/tailwind.config.js
- We weren't purging CSS which had some really bad performance/load time consequences.
- Keep the version endpoint broken for now until we can debug UptimeRobot
> Optimize FE loadtimes + UptimeRobot debugging

- .config/.env-example
- .github/workflows/pr-check-terraform.yml
- Makefile
- apps/api/env.js
- apps/api/src/database/database.module.ts
- docker-compose.yml
I think `NODE_ENV=development` is an anti-pattern and it's adding a bit of confusion, let's discuss these changes and merge if it's an improvement
> Remove NODE_ENV=development

- .github/workflows/pr-check-api.yml
- Makefile
- README.md
- apps/api/jest-e2e.json
- apps/api/package.json
- apps/api/src/app.config.ts
- apps/api/src/database/database.module.ts
- apps/api/src/mail/mail.service.ts
- apps/api/src/submission/submission.service.ts
- apps/api/test/app.e2e-spec.ts
- apps/api/test/fixture/invalidSubmission_firstname.json
- apps/api/test/fixture/validSubmission.json
- apps/api/test/submission.e2e-spec.ts
- apps/api/tsconfig.json
- docker-compose.test.yaml
- yarn.lock
- `make api-integration-test` to run integration tests with a transient postgres container
- Integration tests use their own DB config + env vars
- Test docker-compose for test db + make commands
- Fix up integration test setup
- Extract validationpipe config for use in integration testing
- sendMailable returns void if chesHost doesn't exist
- Add basic tests for submissions
> EHPR-186 | Integration tests

- apps/api/src/app.service.ts
NODE_ENV will always be `production` so let's use `ENV_NAME` which is probably the originally intended variable to expose here
> update version endpoint to give actual env name

- apps/api/src/submission/entity/submission.entity.ts
- apps/api/test/fixture/invalidSubmission_firstname.json
- apps/api/test/fixture/validSubmission.json
- apps/web/src/components/submission/components/Preferences.tsx
- apps/web/src/components/submission/validation/preferences.tsx
- packages/common/src/dto/availability-information.dto.ts
- packages/common/src/interfaces/form-payload.ts
> EHPR-205 Added previous deployment question

- packages/accessibility/src/submission.pa11y-ci.js
We've manually verified the contrast issue is a false positive due to the complex implementation of the third party dropdown library. By adding a specific selector to the `hideElements` property in our accessibility tests we can specifically ignore this false positive
> Ignore react-select / pa11y false positive 

- apps/web/src/components/submission/components/Credential.tsx
See post on slack for video on functionality
> EHPR-230 Added delete functionality to each specialty row

- Makefile
As part of updating the API credentials for CHES, the client ID for ches was changed.
> Updated CHES client ID

- apps/api/src/mail/enums/mail-template.enum.ts
- apps/api/src/mail/mailables/update-confirmation.mailable.ts
- apps/api/src/mail/templates/update-confirmation.hbs
- apps/api/src/submission/submission.service.ts
- terraform/api.tf
- terraform/secrets.tf
> Added confirmation email to update submission flow

- apps/api/package.json
- apps/api/src/app.module.ts
- apps/api/src/database/database.module.ts
- apps/api/src/mass-email-record/entity/mass-email-record.entity.ts
- apps/api/src/mass-email-record/mass-email-record.module.ts
- apps/api/src/mass-email-record/mass-email-record.service.ts
- apps/api/src/migration/1707421827910-AddMassEmailRecordTable.ts
- apps/api/src/registrant/registrant.module.ts
- apps/api/src/registrant/registrant.service.ts
- apps/api/src/user/entity/user.entity.ts
- apps/web/src/components/email/TemplatePreview.tsx
- packages/common/src/dto/email-template.dto.ts
- yarn.lock
- added ability to send mass emails
- added `Promise Pool` for concurrency measures, currently set to 5, can be changed.
- added confirmation modal *added TODO to add legal disclaimer
- added `mass_email_record` table to keep records of all mass email sends
- will create an entry whether successful or not, saving errors
> EHPR-291 - add ability to send mass emails

- apps/api/package.json
- apps/api/src/registrant/registrant.service.ts
- yarn.lock
- added `limiter` library to reduce amount of requests per second to AWS
- set to 35 tokens/ requests per 1 second window
- AWS currently has a max of 40/s
> add limiter library for aws ses sending rates

- apps/api/src/app.module.ts
- apps/api/src/registrant/registrant.controller.ts
- apps/api/src/registrant/registrant.service.ts
- apps/api/src/submission/submission.module.ts
- apps/api/src/submission/submission.service.ts
- apps/web/src/components/Pagination.tsx
- apps/web/src/components/admin/AdminRegistrantsTable.tsx
- apps/web/src/components/admin/AdminSearch.tsx
- apps/web/src/components/general/GeneralCheckbox.tsx
- packages/common/src/constants/authorities.ts
- packages/common/src/dto/registrant-filter.dto.ts
- packages/common/src/helper/is-moh.ts
- add filter by health authority query
- will only show registrants with an interest in deploying to a location within logged in users HA
- add `Show Any Region` checkbox to show registrants with no deployment location preference
- Providence has no region filter access (need to confirm, can take out)
- no access for First Nations/ Provincial ATM (need to confirm)
> EHPR-302 -  filter registrants table by ha

- apps/api/src/scripts/send-data-extract.ts
- apps/web/src/components/submission/components/Review.tsx
- added new form fields to `Review` screen
- added new form fields to submissions extract
> EHPR-275 - add new form fields to extract and review screen

- apps/api/src/app.config.ts
Was getting request limits when sending larger amounts of emails. This fixes that.
> Fix for request size limits

- apps/api/src/registrant/registrant.service.ts
- apps/web/src/services/submission.ts
- apps/web/src/util/index.ts
- apps/web/src/util/validate-confirmation-id.ts
In the security tab CodeQl has new alerts with code
I addressed these as follows
- Enforce a format check for api call
- Made template replacement more secure and faster
> [EHPR] addressing CodeQL alerts

- .github/workflows/deploy-dev.yml
- .github/workflows/pr-zap-prod.yml
- github action failed because of this zap scan version outdated
- upgrade the version to latest 0.12
> EHPR | Upgrade Zap Scan

- .github/workflows/pr-check-web-a11y.yml
- apps/web/src/styles/globals.css
- packages/accessibility/src/submission.pa11y-ci.js
**Note: This PR is merging to the Captcha branch `EHPR-322-2`.**
- Fix a11y workflow broken
- Also fix the workflow version to v4 as it is going to deprecate for older version
- Fix a11y color contrast error
> EHPR-322 | Fix A11y Pipeline 
