bcgov/ehpr2

package.json
tsconfig.json
yarn.lock

https://freshworks.atlassian.net/browse/EHPR-48
As per ticket

EHPR-48 | stricter tsconfig + node14

---

packages/web/components/Footer.tsx
packages/web/components/Header.tsx
packages/web/components/index.tsx
packages/web/pages/_app.tsx
packages/web/styles/globals.css

EHPR-6 | header + footer

---

packages/web/components/Footer.tsx
packages/web/components/Stepper.tsx
packages/web/components/index.tsx
packages/web/next.config.js
packages/web/pages/submission/[step].tsx
packages/web/pages/submission/index.tsx

EHPR-6 | Stepper

---

packages/web/components/Button.tsx
packages/web/components/FormStepHeader.tsx
packages/web/components/form/index.tsx
packages/web/next.config.js
packages/web/pages/_app.tsx
packages/web/pages/index.tsx
packages/web/pages/submission/[step].tsx
packages/web/tailwind.config.js

- per-step validation
- protect pages from direct navigation
- allow routing between complete pages
https://user-images.githubusercontent.com/71518072/143946360-d4143f70-a355-4814-82eb-9ee3cea7222c.mp4

EHPR-6 |  Form Structure

---

.dockerignore
Dockerfile
Makefile
docker-compose.yml
package.json

Ticket: [EHPR-50](https://freshworks.atlassian.net/browse/EHPR-50)

EHPR-50 | Add basic docker support for the application

---

.github/workflows/pr-check.yml
.github/workflows/web-pr-check.yml
apps/web/package.json
apps/web/src/components/submission/index.tsx
apps/web/src/components/submission/validation/contact.tsx
apps/web/src/components/submission/validation/credential.tsx
apps/web/src/components/submission/validation/index.ts
apps/web/src/components/submission/validation/personal.tsx
apps/web/src/components/submission/validation/preferences.tsx
apps/web/src/components/submission/validation/review.tsx
packages/common/src/dto/personal-information.dto.ts
yarn.lock

https://freshworks.atlassian.net/browse/EHPR-57

EHPR-57 | Personal info validation

---

apps/web/src/components/submission/components/Contact.tsx

https://freshworks.atlassian.net/browse/EHPR-77
- Nixed placeholders in favour of helper text (approved by Khanh)

EHPR-77 | Contact form UI

---

apps/web/src/components/form/FormError.tsx
apps/web/src/components/submission/index.tsx
apps/web/src/components/submission/validation/contact.tsx
apps/web/src/components/submission/validation/index.ts
apps/web/src/components/submission/validation/personal.tsx
apps/web/tailwind.config.js
packages/common/src/dto/contact-information.dto.ts

https://freshworks.atlassian.net/browse/EHPR-78

EHPR-78 | contact form validation

---

apps/web/src/components/form/Field.tsx
apps/web/src/components/form/Select.tsx
apps/web/src/components/form/index.ts
apps/web/tests/components/form/Select.test.tsx

https://freshworks.atlassian.net/browse/EHPR-87

EHPR-87 | Add Select Component 

---

apps/web/package.json
apps/web/src/components/form/Field.tsx
apps/web/src/components/form/MultiSelect.tsx
apps/web/src/components/form/Select.tsx
apps/web/src/components/form/index.ts
apps/web/tests/components/form/MultiSelect.test.tsx
apps/web/tests/components/form/Select.test.tsx
yarn.lock

https://freshworks.atlassian.net/browse/EHPR-88

EHPR-88 | Searchable multi select

---

apps/web/src/components/form/Checkbox.tsx
apps/web/src/components/form/index.ts
apps/web/tests/components/form/Checkbox.test.tsx

https://freshworks.atlassian.net/browse/EHPR-89
- Checkbox + CheckboxArray components

EHPR-89 | Add checkbox and CheckboxArray component

---

apps/web/src/components/form/Radio.tsx
apps/web/src/components/form/index.ts
apps/web/tests/components/form/Radio.test.tsx

https://freshworks.atlassian.net/browse/EHPR-90
- Like a checkbox, but you only get one

EHPR-90 | Radio

---

apps/web/src/components/form/Field.tsx
apps/web/src/components/form/Textarea.tsx
apps/web/src/components/form/index.ts
apps/web/tests/components/form/Textarea.test.tsx

https://freshworks.atlassian.net/browse/EHPR-91

EHPR-91 | Textarea

---

.github/workflows/deploy-dev.yml
Makefile

Add basic pipeline to deploy application on aws dev env.

EHPR-76: Add basic deployment pipeline

---

apps/web/src/components/submission/index.tsx

Reimplement 2nd step validation

---

apps/web/src/components/submission/index.tsx

https://freshworks.atlassian.net/browse/EHPR-92

EHPR-92 | add horizontal padding to mobile form

---

.config/.env-example
Makefile
docker-compose.yml
packages/common/jest.config.js
packages/common/package.json
packages/common/src/dto/skill-information.dto.spec.ts
packages/common/tsconfig.json
terraform/api.tf
terraform/db.tf
terraform/main.tf
terraform/network.tf
terraform/security.tf
terraform/variable.tf
yarn.lock

-----------
Ticket: [EHPR-94](https://freshworks.atlassian.net/browse/EHPR-94)

EHPR-94 | Setup remote db

---

Makefile
README.md
apps/web/jest.config.js
apps/web/package.json
apps/web/src/components/submission/index.tsx
apps/web/src/pages/_app.tsx
apps/web/src/services/index.ts
apps/web/src/services/submission.ts
apps/web/tsconfig.json
docker-compose.yml
yarn.lock

This allows us to submit partial form values to the API
**NOTE** You'll either need to run the webapp through docker or add `NEXT_PUBLIC_API_URL=http://localhost:4000/api/v1` to a file called `.env.local` in `apps/web`

Form Submission

---

apps/api/src/.ormconfig.ts
apps/api/src/database/database.module.ts
packages/common/src/dto/index.ts

This PR to fix immediate crash of API lambda.

EHPR-94 | Resolve Database connection

---

Dockerfile
Makefile
apps/web/.babelrc
apps/web/next.config.js
apps/web/package.json
docker-compose.yml
package.json
packages/common/src/hello-world.ts

EHPR-95 | Zero install Docker

---

packages/common/src/dto/availability-information.dto.ts
packages/common/src/dto/contact-information.dto.ts
packages/common/src/dto/form-payload.dto.ts
packages/common/src/dto/personal-information.dto.ts
packages/common/src/dto/placement-preferences.dto.ts
packages/common/src/dto/skill-information.dto.ts

https://freshworks.atlassian.net/browse/EHPR-97
It worked!

EHPR-97 | Optionally apply fields in constructor

---

Makefile
apps/api/src/lambda.ts
apps/api/src/main.ts

EHPR-25 | Create single config for nest app of both lambda and other env

---

.prettierignore
apps/api/src/form/form.service.ts
apps/web/package.json
apps/web/src/components/form/Checkbox.tsx
apps/web/src/components/form/Field.tsx
apps/web/src/components/form/MultiSelect.tsx
apps/web/src/components/form/Select.tsx
apps/web/src/components/submission/components/Credential.tsx
apps/web/src/components/submission/validation/credential.tsx
apps/web/src/components/submission/validation/index.ts
apps/web/tailwind.config.js
apps/web/tests/components/form/Checkbox.test.tsx
apps/web/tests/components/form/Select.test.tsx
apps/web/tests/components/submission/components/Credential.test.tsx
packages/common/src/data/applicant_stream_data.ts
packages/common/src/data/index.ts
packages/common/src/dto/skill-information.dto.ts
packages/common/src/index.ts
packages/common/src/interfaces/form-payload.ts
yarn.lock

https://freshworks.atlassian.net/browse/EHPR-79
Made some changes in `common`, please double check the changes are okay and make sense 👍 
- streamTypes -> stream
- currentEmploymentType -> currentEmployment
I've experienced non-blocking some wierd issues  with React-Select in this implementation, I've spent a bit of time debugging but it feels like weird library stuff, if I had time I would replace it with [downshift](https://github.com/downshift-js/downshift)

EHPR-79 | Credential Page UI

---

apps/web/src/services/submission.ts

https://freshworks.atlassian.net/browse/EHPR-104
400 is better ✔️

EHPR-104 | Fix FE Form submission

---

.github/workflows/pr-check-terraform.yml

Changes to TF directory run all deployment steps except for actually deploying

Add terraform PR check

---

packages/common/src/dto/contact-information.dto.ts

Refer to [EHPR-93](https://freshworks.atlassian.net/browse/EHPR-93)

EHPR-93 fix optional field validation error

---

apps/web/src/components/submission/components/Credential.tsx
apps/web/tests/components/submission/components/Credential.test.tsx

https://freshworks.atlassian.net/browse/EHPR-107

EHPR-107 | Update copy to match designs

---

apps/web/src/components/submission/components/Credential.tsx
apps/web/tailwind.config.js
apps/web/tests/components/submission/components/Credential.test.tsx

https://freshworks.atlassian.net/browse/EHPR-110

EHPR-110 | mobile specialty selector

---

apps/web/src/components/submission/components/Credential.tsx
apps/web/tests/components/submission/components/Credential.test.tsx

https://freshworks.atlassian.net/browse/EHPR-111

EHPR-111 | Reorder credential questions

---

apps/web/src/components/submission/components/Credential.tsx

https://freshworks.atlassian.net/browse/EHPR-133
Add a switching component to render specific questions based on the answer to employment question

EHPR-133 | HA question label text

---

apps/web/src/components/submission/components/Personal.tsx
apps/web/src/pages/submission/[step].tsx

https://freshworks.atlassian.net/browse/EHPR-143

EHPR-143 | Copy Changes

---

apps/web/package.json
apps/web/src/components/Disclosure.tsx
apps/web/src/components/form/Radio.tsx
apps/web/src/components/index.tsx
apps/web/src/components/submission/components/Preferences.tsx
apps/web/src/components/submission/index.tsx
apps/web/src/components/submission/validation/index.ts
apps/web/src/components/submission/validation/preferences.tsx
apps/web/tailwind.config.js
packages/common/src/data/location_data.json
packages/common/src/dto/availability-information.dto.ts
packages/common/src/helper/index.ts
packages/common/src/helper/locationData.ts
yarn.lock

https://freshworks.atlassian.net/browse/EHPR-45

EHPR-45 | Preferences -> Location Questions

---

apps/api/src/common/helper/csv/submissionExport.ts
apps/api/src/submission/submission.service.ts
apps/web/src/components/submission/components/Credential.tsx
apps/web/src/components/submission/validation/credential.tsx
apps/web/tests/components/submission/components/Credential.test.tsx
packages/common/src/dto/skill-information.dto.ts
packages/common/src/helper/applicantStreamData.ts

https://freshworks.atlassian.net/browse/EHPR-149

EHPR-149 | Additional comments for non-clinical

---

.config/.env-example
.gitignore
Makefile
apps/api/package.json
apps/api/src/database/database.module.ts
apps/api/src/migration/1640046687865-AddSubmissionEntity.ts
apps/api/src/ormconfig.ts

https://freshworks.atlassian.net/browse/EHPR-114
Just had to reconfigure `ormconfig.ts` and modify some scripts to get it working, the key seems to be `migrationsRun`

EHPR-114 | Migrations

---

Makefile
apps/web/src/services/submission.ts

- Makefile was referencing old ormconfig filename
- FE POST wasn't updated

Fix build issues

---

apps/web/src/components/Button.tsx
apps/web/src/components/submission/components/Credential.tsx
apps/web/src/components/submission/components/Review.tsx
apps/web/src/components/submission/validation/credential.tsx
apps/web/src/pages/confirmation.tsx
packages/common/src/dto/skill-information.dto.ts

https://freshworks.atlassian.net/browse/EHPR-49

EHPR-49 | Review First 3 steps (+Fix for  EHPR-163)

---

.github/workflows/deploy-test.yml
Makefile
apps/api/src/app.controller.spec.ts
apps/api/src/app.controller.ts
apps/api/src/app.service.ts
apps/api/src/migration/1640046687865-AddSubmissionEntity.ts
apps/api/src/ormconfig.ts
docker-compose.yml
terraform/api.tf
terraform/secrets.tf
terraform/variable.tf

- Test Env infra code
- Cleanup 
- Pipeline

EHPR-25 | Setup test env and deployment pipeline

---

apps/api/src/submission/submission.service.ts
apps/web/src/pages/confirmation.tsx

Note - We will need to strip out dashes if we need to accept a confirmation code from the client. 
I've also tacked on EHPR -145 - add dashes to email template, and added some helper methods.

EHPR - 141 Added dashes to displayed code

---

apps/web/src/components/submission/components/Credential.tsx
packages/common/src/data/applicant_stream_data.json
packages/common/src/dto/is-array-of-specialties.decorator.ts

Fixed validator to allow for streams that contain no specialties 
Updated data object to correctly have empty specialty arrays.

EHPR - 136 Fixed data issue and verification check issue

---

apps/api/src/app.config.ts
apps/web/src/components/submission/components/Contact.tsx
packages/common/src/dto/contact-information.dto.ts

https://freshworks.atlassian.net/browse/EHPR-134

EHPR-134 | extension field not validated

---

apps/web/src/components/submission/components/Preferences.tsx

https://freshworks.atlassian.net/browse/EHPR-172
This fixes Issue #2, #1 is already resolved

EHPR-172 | Responsive columns for locations selector

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-test.yml
apps/api/src/mail/mail.module.ts

I forgot to add logger to the mail module

Fix submisson

---

apps/web/src/components/submission/components/Contact.tsx

https://freshworks.atlassian.net/browse/EHPR-175

EHPR-175 | Responsive columns on contact page

---

apps/web/src/components/submission/validation/credential.tsx

https://freshworks.atlassian.net/browse/EHPR-168

EHPR-168 | Update registration status answer labels

---

apps/web/src/components/submission/validation/credential.tsx
packages/common/src/interfaces/form-payload.ts

https://freshworks.atlassian.net/browse/EHPR-152

EHPR-152 | Update HA options

---

apps/web/src/components/submission/components/Credential.tsx

https://freshworks.atlassian.net/browse/EHPR-167

EHPR-167 | Remove training from subspecialty label

---

.config/.env-example
Makefile

https://freshworks.atlassian.net/browse/EHPR-148

EHPR-148 | Update from address

---

packages/common/src/data/applicant_stream_data.json

https://freshworks.atlassian.net/browse/EHPR-151
Ran the debugged script on the latest data sheet
- Student is removed as a stream + subspecialties
- Various erroneous specialties and subspecialties are fixed

EHPR-151 | Remove erroroneous specialties, remove student

---

apps/web/src/components/form/Radio.tsx

apply min width to checkbox to prevent shrinkage

---

apps/web/src/pages/confirmation.tsx

Removed the last vestiges of the PDF button.

EHPR - 156 Removed PDF button 

---

apps/web/src/components/submission/components/Review.tsx

Optional fields need conditional rendering
https://freshworks.atlassian.net/browse/EHPR-179

EHPR-179 | Remove extraneous label

---

apps/web/src/components/submission/index.tsx

https://freshworks.atlassian.net/browse/EHPR-183

EHPR-183 | Conditional continue button text

---

apps/web/src/components/submission/index.tsx

https://freshworks.atlassian.net/browse/EHPR-180

EHPR-180 | Form button text

---

apps/api/src/mail/mailables/confirmation.mailable.ts

https://freshworks.atlassian.net/browse/EHPR-181

EHPR-181 | Update confirmation email subject line

---

apps/web/src/components/submission/components/Contact.tsx
apps/web/src/components/submission/components/Credential.tsx
apps/web/src/components/submission/components/Personal.tsx
apps/web/src/components/submission/components/Review.tsx
apps/web/src/pages/submission/[step].tsx
apps/web/tests/components/submission/components/Credential.test.tsx
packages/common/src/dto/personal-information.dto.ts

https://freshworks.atlassian.net/browse/EHPR-182
Cancelled AC5 as per design

EHPR-182 | UI fixes

---

apps/web/src/components/submission/components/Credential.tsx

https://freshworks.atlassian.net/browse/EHPR-193

EHPR-192 | Remove add btn if specialty selector is disabled

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-test.yml
.github/workflows/pr-check-terraform.yml
Makefile

- Create SSL certificate on respective aws workspace account
- Copy associated CNAME record/value from certificate and create entry on *.freshoworks.club hosted zone 
- Create CNAME entry with respective domain name in *.freshoworks.club hosted zone.

EHPR-146 | Setup dev/test vanity url

---

.sonarcloud.properties

Configured according to https://developer.gov.bc.ca/SonarQube-on-OpenShift#sonarcloud

EHPR-115 | Add base sonarcloud config

---

apps/api/src/app.config.ts

https://freshworks.atlassian.net/browse/EHPR-117
Fixed as per suggestion: https://sonarcloud.io/project/security_hotspots?id=bcgov_ehpr2&hotspots=AX5FZ-pzNVtMtOJ2Z7ZC

EHPR-199 | Disable x-powered-by to mitigate fingerprinting

---

apps/api/src/mail/mail.service.ts
apps/api/src/submission/entity/submission.entity.ts
apps/api/src/submission/submission.service.ts
apps/web/src/components/Alert.tsx
apps/web/src/components/Disclosure.tsx
apps/web/src/components/submission/validation/credential.tsx

Fixed Extra large icons issue 
Fixed issue whereby subspecialties were getting stripped out of the entity on submission

EHPR-203 Fixed extra large icons

---

apps/api/src/submission/entity/submission.entity.ts
apps/api/test/fixture/invalidSubmission_firstname.json
apps/api/test/fixture/validSubmission.json
apps/api/test/submission.e2e-spec.ts
apps/web/src/components/submission/components/Preferences.tsx
apps/web/src/components/submission/components/Review.tsx
apps/web/src/components/submission/validation/preferences.tsx
packages/common/src/dto/availability-information.dto.ts
packages/common/src/interfaces/form-payload.ts
packages/common/src/validators/validate-array.decorator.ts

Ticket: [EHPR-206](https://freshworks.atlassian.net/browse/EHPR-206)

EHPR-206 | Adding deployment type question (part 1)

---

apps/web/src/components/submission/components/Preferences.tsx

https://freshworks.atlassian.net/browse/EHPR-207

EHPR-207 | Update previous deployment question for new keys

---

.gitignore
apps/web/src/components/form/Select.tsx
apps/web/src/components/submission/components/Credential.tsx
apps/web/tests/components/form/Select.test.tsx
packages/common/src/dto/credential-information.dto.ts
packages/common/src/validators/is-array-of-specialties.decorator.ts

- show disabled select options
- remove invalid subspecialties when changing a specialty

Fix specialty selection

---

terraform/cloudfront/response.js

I want to do a test to confirm that removing the unsafe inline from the CSP will break the site.

227/228 Remove unsafe inline

---

.github/workflows/ci-zap.yml
.zap/rules.tsv
Makefile
terraform/api.tf
terraform/cloudfront.tf
terraform/cloudfront/request.js

Fixes - Proxy, Error disclosure and HSTS errors. 
https://freshworks.atlassian.net/browse/EHPR-224
https://freshworks.atlassian.net/browse/EHPR-220

ZAP Scan fixes #1

---

apps/web/src/pages/submission/[step].tsx

Removed extra `be` from new copy

Removed typo

---

apps/api/src/submission/submission.service.ts
apps/web/src/components/Link.tsx
apps/web/src/components/submission/components/UpdateSubmissionForm.tsx
apps/web/src/components/update/UpdateSubmissionHeader.tsx
apps/web/src/pages/submission/[step].tsx
apps/web/src/pages/update-submission.tsx
apps/web/src/pages/update-submission/confirmation.tsx

Updated copy on landing page
Added confirmation page for after submission update.

Completed work on EHPR-281 Add confirmation page for profile update

---

.config/.env-example
Makefile
apps/api/package.json
apps/api/src/cron.ts
apps/api/src/database/database.module.ts
apps/api/src/scripts/send-data-extract.ts
apps/api/src/submission/submission.controller.ts
apps/api/src/submission/submission.service.ts
packages/common/src/helper/locationData.ts
terraform/cron.tf
terraform/main.tf
terraform/secrets.tf
yarn.lock

- Add Lambda function to extract submissions and send them as a spreadsheet to the registered recipients
- Schedule extraction at 2PM UTC(7AM PST) on every Monday
- List of recipients' email needs to be stored AWS Parameter Store.

EHPR-272 schedule data extract

---

.config/.env-example
Makefile
docker-compose.yml
keycloak/realm-ehpr.json

- Add Keycloak service to docker-compose for dev and testing
- Use the default embedded database instead of an external
- Enable service-account

ehpr-284 deploy local Keycloak container

---

.config/.env-example
Makefile
apps/web/next.config.js
apps/web/package.json
apps/web/src/components/Header.tsx
apps/web/src/components/Logout.tsx
apps/web/src/pages/_app.tsx
apps/web/src/pages/admin/index.tsx
apps/web/src/pages/login.tsx
docker-compose.yml
keycloak/realm-ehpr.json
yarn.lock

EHPR-277 login page

---

terraform/api.tf

- added domain variable to environment list in `api.tf`

 EHPR-294 - add domain to api env variables

---

apps/api/src/admin/admin.controller.ts
apps/api/src/app.module.ts
apps/api/src/registrant/registrant.controller.ts
apps/api/src/registrant/registrant.module.ts
apps/api/src/registrant/registrant.service.ts
apps/api/src/submission/submission.service.ts
apps/api/src/submission/submission.util.ts
apps/web/jest.config.js
apps/web/src/components/Pagination.tsx
apps/web/src/components/SearchInput.tsx
apps/web/src/components/admin/AdminRegistrantsTable.tsx
apps/web/src/components/admin/AdminSearch.tsx
apps/web/src/components/admin/AdminTabs.tsx
apps/web/src/components/admin/index.ts
apps/web/src/constants/admin.ts
apps/web/src/constants/index.ts
apps/web/src/constants/specialties.ts
apps/web/src/pages/admin/index.tsx
apps/web/src/services/admin.ts
apps/web/src/services/index.ts
apps/web/src/services/registrant.ts
apps/web/src/util/convert-params.ts
apps/web/src/util/index.ts
apps/web/tsconfig.json
packages/common/src/dto/index.ts
packages/common/src/dto/registrant-filter.dto.ts
packages/common/src/ro/index.ts
packages/common/src/ro/registrant.ro.ts

- added pagination
- added table to view registrants
- added search filters `first name`, `last name` and `email`
- added 3 tabs for user invite, download extract and registrants
- user invite tab only visible to admin users
Admin view
- [EHPR-290](https://eydscanada.atlassian.net/jira/software/c/projects/EHPR/boards/260?selectedIssue=EHPR-290)

EHPR-290 - add pagination, view and search registrants table

---

apps/api/src/admin/admin.service.ts

- removed extra slash preventing hyperlink from being valid in invite email
- [EHPR-294](https://eydscanada.atlassian.net/jira/software/c/projects/EHPR/boards/260?selectedIssue=EHPR-294)

EHPR-294 - fix hyperlink in invite email

---

apps/api/src/registrant/registrant.service.ts

- increased concurrency limit to 15

up concurrency to 15 for mass emails

---

apps/api/src/registrant/registrant.service.ts

- lower concurrency limit to 10 to see if it helps with AWS sending limits

lower concurrency limit to 10

---

apps/api/src/app.module.ts
apps/api/src/auth/auth.guard.ts
apps/api/src/database/database.module.ts
apps/api/src/migration/1708532257590-AddHaTableAndHaIdFKToUserTable.ts
apps/api/src/user/entity/ha.entity.ts
apps/api/src/user/entity/user.entity.ts
apps/api/src/user/user.module.ts
apps/api/src/user/user.service.ts
packages/common/src/constants/authorities.ts
packages/common/src/constants/index.ts
packages/common/src/helper/index.ts
packages/common/src/helper/is-moh.ts
packages/common/src/index.ts
packages/common/src/interfaces/user.ts

- added migration for `health_authority` table
- add `ha_id` column and relation to `user` table
- update `ha_id` for existing users using their email domain
- prelim work for retrieving users HA for future filtering purposes
[EHPR-301](https://eydscanada.atlassian.net/jira/software/c/projects/EHPR/boards/260?selectedIssue=EHPR-301)

EHPR-301 - add health authority table and assign ha id to users

---

apps/api/test/fixture/validSubmission.json
apps/web/src/components/form/MultiSelect.tsx
apps/web/src/components/submission/components/Credential.tsx
apps/web/src/components/submission/components/Preferences.tsx
apps/web/src/components/submission/components/Review.tsx
apps/web/src/components/submission/validation/credential.tsx
apps/web/src/components/submission/validation/index.ts
apps/web/src/components/submission/validation/preferences.tsx
apps/web/src/constants/specialties.ts
apps/web/src/pages/submission/[step].tsx
apps/web/tests/components/submission/components/Credential.test.tsx
packages/common/src/data/applicant_stream_data.json
packages/common/src/dto/preferences-information.dto.ts
packages/common/src/interfaces/form-payload.ts

- confirmation of which HA's to show in previous deployment dropdown
- Split “Emergency Responder” stream type into (i) Paramedic and (ii) Firefighter. Subspecialities for Paramedic to include (i) EMR, (ii) PCP, (iii) ACP, (iv) Critical Care (CCP). Subspeciality for Firefighter to include only FR (Fire First responder).
- add conditional fields for `Have you previously been deployed from the EHPR?` = `Yes`
- Date of Last Deployment and Last Deployed Health Authority
- update `Indicate the maximum duration of deployment you are willing to support` options
- update landing page text, added `You will be required to undergo a criminal record check or criminal record check verification under the Criminal Records Review Act prior to any deployment. Individuals who forgo the criminal record …

EHPR-275 - form updates

---

packages/common/src/data/applicant_stream_data.json

- make specialties list alphabetical again after adding `Paramedic` and `Firefighter`

make specialties list alphabetical

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-test.yml

continuation of https://github.com/bcgov/ehpr2/pull/217

EHPR update migrate away from tf cloud

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-test.yml
.github/workflows/pr-check-terraform.yml
Makefile
apps/api/package.json
apps/api/src/app.module.ts
apps/api/src/migration/1709146531951-AddWithdrawnReasonToSubmissionTable.ts
apps/api/src/registrant/registrant.controller.ts
apps/api/src/registrant/registrant.module.ts
apps/api/src/registrant/registrant.service.ts
apps/api/src/submission/entity/submission.entity.ts
apps/api/src/submission/submission.service.ts
apps/web/src/pages/unsubscribe/index.tsx
apps/web/src/services/registrant.ts
packages/common/src/constants/index.ts
packages/common/src/constants/unsubscribe-reasons.ts
packages/common/src/dto/index.ts
packages/common/src/dto/unsubscribe-reason.dto.ts
terraform/api.tf
terraform/main.tf
terraform/secrets.tf
yarn.lock

- create envs for jwt secret
- confirm list of reasons for unsubscribing (from client)
- confirm wording for both unsubscribe page and success page
- format unsubscribe link in email better
- add unique unsubscribe link to each email
- use JWT 
- add unsubscribe page with dropdown listing reasons for unsubscribing
- add success page once user submits reason for unsubscribing
- make registrant 'withdrawn' upon unsubscribing
- remove 'withdrawn' registrants from data extract and registrant table
[EHPR-299](https://eydscanada.atlassian.net/browse/EHPR-299)

EHPR-299 add unsubscribe link and reason

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-test.yml
apps/api/src/registrant/registrant.controller.ts
apps/web/src/constants/admin.ts
packages/common/src/helper/feature-flags.ts
packages/common/src/helper/index.ts

- add mass email feature flag to block access to mass email route and hide registrants table

EHPR-306 - add mass email feature flag

---

apps/api/package.json
apps/api/src/submission/submission.service.ts
yarn.lock

This change will allow the test to run locally without the need of AWS credentials.

[EHPR] Integration test fix for local

---

apps/web/src/components/Alert.tsx
apps/web/src/pages/admin/index.tsx
apps/web/tailwind.config.js

Added an alert warning Health Authority users to submit a request to access before downloading the registry.
Updated the alert component to have multiple colour options.

EHPR - Quick release

---

Makefile
apps/api/src/submission/submission.service.ts

FNHA users should only be able to extract users who are willing to work anywhere.

EHPR - 339 Added filters for FNHA

---

apps/web/src/components/submission/validation/preferences.tsx
packages/common/src/data/location_data.json

EHPR-340 | Add FNHA dropdown in section 4

---

apps/api/src/submission/submission.service.ts
packages/common/src/constants/authorities.ts

Add FNHA to list of full HAs
Added a check to safely return when there is no submissions

EHPR-339 Added FNHA to full list of HAs

---

terraform/db.tf

Set non prod db to be a t3 medium instead of a r5 large

Updated non prod db size to be smaller

---

apps/api/src/admin/admin.controller.ts
apps/api/src/submission/submission.service.ts
apps/web/src/components/admin/ExtractSubmissions.tsx
apps/web/src/components/form/ListboxSelect.tsx
apps/web/src/components/submission/components/Credential.tsx
apps/web/src/services/admin.ts
packages/common/src/dto/extract-applicants-filter.dto.ts
packages/common/src/dto/index.ts

Changes 
1. Added Stream multi-select dropdown on extract page
2. Added Specialty multi-select dropdown on extract page
3. Added Subspecialty multi-select dropdown on extract page
4. Added location multi select drop down 
5. Location multi select is only shown if the user is MoH
6. Updated extract to apply filters 
Note - Parsing submission json down to levels to get subspecialties proved difficult. I put the filtering logic outside of the query.

Ehpr 335 enable filtered reporting 

---

apps/web/src/components/admin/AdminRegistrantsTable.tsx
apps/web/src/components/tiptap/TipTapEditor.tsx
apps/web/src/constants/locations.ts

EHPR/IEN 971 Fix deployment locations display and fix lineheight in email template

---

apps/api/src/submission/submission.service.ts
apps/api/test/submission.e2e-spec.ts
apps/web/src/components/submission/components/UpdateSubmissionForm.tsx
apps/web/src/components/update/UpdateSubmissionHeader.tsx
packages/common/src/dto/index.ts
packages/common/src/dto/update-preferences-information.dto.ts
packages/common/src/dto/update-submission.dto.ts

* Added new First Nations Training questions to the form
* Updated text on update form

EHPR - Form updates

---

apps/api/src/scripts/send-data-extract.ts

EHPR - Added First nations experience questions to extract
